### ISSUE TITLE
How to change ID3 Tags in MP3 File

### ISSUE THREAD

**Issue by tariqwebstar** [cfjedimaster/Cordova-Examples#11]
I just saw Working with MP3s, ID3, and PhoneGap/Cordova. I just want to ask how to change or update ID3 Tags from mp3 file

**Comment by cfjedimaster** [comment]
I'm not aware of any client-side lib that would do this. There is a Node
module, https://www.npmjs.com/package/id3-writer, that you could try
converting.

On Mon, May 4, 2015 at 1:35 AM, tariqwebstar <notifications@github.com>
wrote:

> I just saw Working with MP3s, ID3, and PhoneGap/Cordova. I just want to
> ask how to change or update ID3 Tags from mp3 file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/Cordova-Examples/issues/11>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by tariqwebstar** [comment]
Thanks for your reply. Basically I'm creating an mobile app. I want to download a song from server and after that I'll have to modify ID3 tags. I'm using ionic framework for my app. I can't use Node. Could you please suggest me more options within the scope of javascript, phonegap/cordova etc ?

**Comment by cfjedimaster** [comment]
Sorry, I can't at the moment. I didn't say to *use* Node, but to look at
the code and see if you can repurpose it.

On Tue, May 5, 2015 at 2:00 AM, tariqwebstar <notifications@github.com>
wrote:

> Thanks for your reply. Basically I'm creating an mobile app. I want to
> download a song from server and after that I'll have to modify ID3 tags.
> I'm using ionic framework for my app. I can't use Node. Could you please
> suggest me more options within the scope of javascript, phonegap/cordova
> etc ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/Cordova-Examples/issues/11#issuecomment-98975175>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by tariqwebstar** [comment]
thanks
