### ISSUE TITLE
contact picker problem

### ISSUE THREAD

**Issue by jawojawo** [cfjedimaster/Cordova-Examples#12]
when i tried to copy the code and convert it to apk using build.phonegap.com its not working not even alert for error message do u think i have error in installation or wrong file has been uploaded to the site?

**Comment by cfjedimaster** [comment]
Did you edit your config.xml to specify the plugins? See the PhoneGap Build docs for how to do that.

**Comment by jawojawo** [comment]
fast reply thanks, i use cli comand cordova plugin add org.apache.cordova.contacts  i also tried cordova plugin add cordova-plugin-contacts cause its saying that they rename the latest plugin. im new to cordova im just trying my first app but im having a little difficulty i dont know if its in my installation or the cordova version itself

**Comment by cfjedimaster** [comment]
What you are doing applies to working with Cordova locally. It is different with PhoneGap Build. Please read their docs as they clearly say how to use plugins. You just need to edit one file.

**Comment by jawojawo** [comment]
i created phonegap and cordova project for the contactpickerui, i copied your www folder to my www folder then i add a plugin "cordova plugin add org.apache.cordova.contacts" then run cordova build android and i also tried to the phonegap project

**Comment by jawojawo** [comment]
ei buddy sorry to waste your time haha, i thought i dont need sdk cause i thought build.phonegap.com can handle the program anyway its working now after i download and install sdk for about 2 days thanks a lot im looking forward to review your other tutorials

**Comment by cfjedimaster** [comment]
k
