### ISSUE TITLE
E/FileTransfer﹕ {"target":"file:\/\/\/data\/data\/pckg\/files\/image.png","http_status":0,"code":3,"source":"http://serverpath/image.png","exception":"socket failed: EMFILE (Too many open files)"}

### ISSUE THREAD

**Issue by BilelKrichen** [cfjedimaster/Cordova-Examples#17]
Hi, I Have a question about checkandDownload Example when i download more than 1000 images from server to DataDirectory store but this error shown <br>
<b>E/FileTransfer﹕ {"target":"file:\/\/\/data\/data\/pckg\/files\/image.png","http_status":0,"code":3,"source":"http://serverpath/image.png","exception":"socket failed: EMFILE (Too many open files)"}</b><br>
How can i fix this Error? 
Please I need Help 
Thanks

**Comment by cfjedimaster** [comment]
Not sure what I can do about that. I'd urge you *not* to download 1k files though. I'd just download one zip and extract it.

**Comment by cfjedimaster** [comment]
See this for an example: http://www.raymondcamden.com/2015/05/19/working-with-the-new-phonegapcordova-contentsync-plugin
