### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by danicarla** [cfjedimaster/Cordova-Examples#23]
Hi Guys.

I copied the code exactly as in the example, but does not work .
I'm generating the .apk file and installing on my android device... but when I connect the USB can not find the file " log.txt " Editar

**Comment by cfjedimaster** [comment]
A couple of things.

1) This repo contains *many* different sample applications. When you say "example", which example do you mean?

That's it actually.

**Comment by danicarla** [comment]
Hi Raymond.. 
Sorry , I have not yet affinity with Github , I was referring to [writelog](https://github.com/cfjedimaster/Cordova-Examples/tree/master/writelog)

**Comment by cfjedimaster** [comment]
When you remote debug, what do you see in the console?

**Comment by danicarla** [comment]
In console say: worked
![errodebug](https://cloud.githubusercontent.com/assets/13678818/16058142/57a42b0c-3253-11e6-80ac-4426b73190d7.jpg)

**Comment by cfjedimaster** [comment]
Ok... so what exactly is going wrong?

**Comment by danicarla** [comment]
When I connect my Android device in  computer using USB cable, I don't find the file "log.txt"

**Comment by cfjedimaster** [comment]
Where are you thinking you will find it?

On Wed, Jun 15, 2016 at 7:34 AM, Dani Carla <notifications@github.com>
wrote:

> When I connect my Android device in computer using USB cable, I don't find
> the file "log.txt"
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cfjedimaster/Cordova-Examples/issues/23#issuecomment-226173685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYBvDVhtVlAI6sS419IKDZNeEEnKlOqks5qL_FtgaJpZM4I0q__>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by danicarla** [comment]
I believed that he would be created somewhere within my Android device

**Comment by cfjedimaster** [comment]
Ah, so cordova.file.dataDirectory is "private" which means the app can see it, but it isn't available externally. See the docs (https://www.npmjs.com/package/cordova-plugin-file) for other path aliases that would allow for external usage.
