### ISSUE TITLE
Barcode example not working properly

### ISSUE THREAD

**Issue by Shreya99r** [cfjedimaster/Cordova-Examples#24]
On running this app on hybrid mobile environment (cordova) ; camera gets initialized with a rectangular space along with a blinking line with it.When a barcode is put in front of the scanner(camera of the device) ,it doesn't scans anything.using the example https://github.com/cfjedimaster/Cordova-Examples/tree/master/barcode .Please help regarding this.

**Comment by cfjedimaster** [comment]
If you remote debug, do you see any errors? If you are pointing at a valid bar code and it just doesn't pick it up, you may need to file a bug report with the author of the plugin.

**Comment by Shreya99r** [comment]
The code now works properly.I tried it on another device's camera with a better quality camera in it.Previously I was using it with 5MP camera.

**Comment by 2016lalu** [comment]
Barcode scanning in hybrid application required high quality camera ...
