### ISSUE TITLE
Can you please let me know how to implement this in ionic 1

### ISSUE THREAD

**Issue by pallaviMN** [cfjedimaster/Cordova-Examples#26]

**Comment by cfjedimaster** [comment]
There are about 30 different demos in this repository. Please document which you mean.

**Comment by pallaviMN** [comment]
I want shake to refresh for ionic 1

**Comment by cfjedimaster** [comment]
I answered you on your blog comment. In the future, please just ask in one place - there's no need to ask in multiple locations.
