### ISSUE TITLE
its not issue, just request, didnt find app where i can ofline sqlite data sync with rempte server. 

### ISSUE THREAD

**Issue by sachin0606** [cfjedimaster/Cordova-Examples#32]
Hi, 

thanks for such large list of examples.  but i wanted to know how i can make offline sqlite data sync with remote (may be aws rds) 

thanks in advance.

**Comment by cfjedimaster** [comment]
This really isn't the place for requests like this, generally I ask people contact me. I'd look into PouchDB - as it has a sync library.
