### ISSUE TITLE
Question on Versions that works with barcode scanner

### ISSUE THREAD

**Issue by dunisani** [cfjedimaster/Cordova-Examples#35]
Hello

I have been struggling to get barcode scanner  to work getting 'write settings false' error.

I would like to ask a question, which versions was the barcode scanner tested using so we can also use the correct versions?
What versions of:
Cordova?
Android sdk?
barcodescanner plugin?

Thank you

**Comment by cfjedimaster** [comment]
Unfortunately I don't remember. But if you are having issues with the plugin, the best place to discuss it would be the GitHub repo for the plugin itself.
