### ISSUE TITLE
SMSComposer not working with direct Phonegap Desktop App.

### ISSUE THREAD

**Issue by NisTa24** [cfjedimaster/Cordova-Examples#37]
Hello Raymond sir, the SMS Composer did not work with the Phonegap desktop app. I tried sending SMS but failed to work, should I build it with the cordova plugins to run it android or is there something else wrong? Please help.

**Comment by cfjedimaster** [comment]
I believe the desktop app is limited to what plugins it supports, right? I'd use a simulator or a real device. Most likely a real device as I'm not sure if SMS works on the simulator.

**Comment by NisTa24** [comment]
I did run it on a real device with the Phonegap Developer app in android throught the IP address given in the desktop phonegap app but still did not work.

**Comment by cfjedimaster** [comment]
That too has locked down plugins.

**Comment by NisTa24** [comment]
ok so then i have to build in apk?

**Comment by cfjedimaster** [comment]
Yes - you can `cordova run android` to do it quickly for you - assuming you've got the Android SDK setup.

**Comment by NisTa24** [comment]
Thank You so much Raymond sir.
