### ISSUE TITLE
having problem in adding plugins

### ISSUE THREAD

**Issue by KerryTucker** [cfjedimaster/Cordova-Examples#38]
![image](https://user-images.githubusercontent.com/39943147/42633690-b1070096-85fa-11e8-8ad3-080784e6a290.png)

help me out

**Comment by fangxiaopeng** [comment]
The right install method should be as follows

cordova plugin add pluginPath

or:

cordova plugin add pluginId

Just try it!

**Comment by KerryTucker** [comment]
what is plugin ID???

**Comment by cfjedimaster** [comment]
@KerryTucker This is not a general support forum for working with Cordova plugins. Please use StackOverflow for that. The correct install is `cordova plugin add cordova-plugin-contacts`. But note that the plugin is deprecated.
